backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "SSG/src/assets/blog"
public_folder: "/assets/blog/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "SSG/src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      